os: linux
dist: xenial
language: cpp

env:
  global:
    - BUILD_TYPE=Debug
    - GENERATOR="Unix Makefiles"
    - JOBS=2

matrix:
  include:
    - compiler: gcc
      env:
        - COMPILER=g++-7
      addons:
        apt:
          update: true
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
    - compiler: clang
      env:
        - COMPILER=clang++-6.0
      addons:
        apt:
          update: true
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-6 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

script:
  - export CXX=${COMPILER}
  - ${CXX} --version
  - cmake --version
  - python --version
  - pyenv global 3.7.1
  - mkdir build && cd build
  - cmake -G "${GENERATOR}" -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build . -- -j${JOBS}
